import {defineField, defineType} from 'sanity'

export default defineType({
  name: 'booking',
  title: 'Booking Section',
  type: 'document',
  fields: [
    defineField({
      name: 'label',
      title: 'Label',
      type: 'string',
      description: 'Section label (e.g., "Book Now")',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heading',
      title: 'Heading',
      type: 'text',
      description: 'Main heading',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'description',
      title: 'Description',
      type: 'text',
      description: 'Booking description text',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'airbnbButtonText',
      title: 'Airbnb Button Text',
      type: 'string',
      description: 'Text for the Airbnb button (e.g., "View on Airbnb")',
      validation: (Rule) => Rule.required(),
      initialValue: 'View on Airbnb',
    }),
    defineField({
      name: 'airbnbUrl',
      title: 'Airbnb URL',
      type: 'url',
      description: 'Full Airbnb listing URL',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'vrboButtonText',
      title: 'VRBO Button Text',
      type: 'string',
      description: 'Text for the VRBO button (e.g., "View on VRBO")',
      validation: (Rule) => Rule.required(),
      initialValue: 'View on VRBO',
    }),
    defineField({
      name: 'vrboUrl',
      title: 'VRBO URL',
      type: 'url',
      description: 'Full VRBO listing URL',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'contactQuestionText',
      title: 'Contact Question Text',
      type: 'string',
      description: 'Text above the contact email (e.g., "Questions about your stay?")',
      validation: (Rule) => Rule.required(),
      initialValue: 'Questions about your stay?',
    }),
    defineField({
      name: 'contactEmail',
      title: 'Contact Email',
      type: 'string',
      description: 'Email address for inquiries',
      validation: (Rule) => Rule.required().email(),
    }),
  ],
})
